name: Scheduled automation
on:
    schedule:
        - cron: "28 12 * * *" # every day at 08:00 UTC   minutes hours day of month month day of week
    workflow_dispatch:        
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v5
            - name: Run automation script
              working-directory: .github/workflows
              run: uv run main.py